[package]
authors = ["Mark Hintz <markinportland7@gmail.com>"]
name = "lsystem"
version = "0.1.0"

[dependencies]
arcball-cgmath = "*"
cgmath = { path = "../cgmath-rs", branch = "unified" }
glium = "0.13.5"
glm = "*"
matrixstack = "*"
num = "*"
