[package]
name = "lsystem"
version = "0.1.0"
authors = ["Mark Hintz <markinportland7@gmail.com>"]

[dependencies]
glium = "0.13.5"
cgmath = "0.8.0"
arcball-cgmath = "0.3.2"
num = "0.1"
matrixstack = "0.1.1"
